project:
  type: website

website:
  title: "test-quarto-include"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts_bar.qmd
      - posts_foo.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

